// Centralized color tokens for web and mobile
export const colors = {
  light: {
    background: '#fff',
    foreground: '#222',
    primary: '#FF6F61',
    primaryForeground: '#fff',
    secondary: '#F5F5F5',
    secondaryForeground: '#222',
    accent: '#FFD700',
    accentForeground: '#222',
    muted: '#E0E0E0',
    mutedForeground: '#888',
    destructive: '#E53935',
    destructiveForeground: '#fff',
    border: '#E0E0E0',
    input: '#F5F5F5',
    ring: '#FF6F61',
  },
  dark: {
    background: '#222',
    foreground: '#fff',
    primary: '#FF6F61',
    primaryForeground: '#222',
    secondary: '#333',
    secondaryForeground: '#fff',
    accent: '#FFD700',
    accentForeground: '#222',
    muted: '#444',
    mutedForeground: '#bbb',
    destructive: '#E53935',
    destructiveForeground: '#fff',
    border: '#444',
    input: '#333',
    ring: '#FF6F61',
  },
} as const;
